# Automations go here...
- alias: 'Lights on in the evening'
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.all_lights
      transition: 1800
      brightness: 130
      color_temp: 370

- alias: "Notify Loungeroom Motion"
  trigger:
    - platform: state
      entity_id: binary_sensor.lounge_room_motion
      to: "Detected"
  action:
    service: notify.mobile_app_gareth_iphone
    data:
      message: "{{ state_attr('binary_sensor.lounge_room_motion', 'friendly_name') }} Detected"
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Motion-In-Living-Room.wav"
