# Main home-assistant config
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 35
  unit_system: metric
  time_zone: Australia/Brisbane
  customize: !include customize.yaml
  auth_providers:
   - type: legacy_api_password
     api_password: !secret api_password
   - type: homeassistant

# Load default platforms
default_config:
discovery:
ssdp:
zeroconf:
# Use the recorder
recorder:
# Use the logbook
logbook:
# Activate the configuration editor
config:
  
# Check for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Force load of IOS component
#ios:

# Allow camera streaming
stream:

# Shopping List Intent
shopping_list:

# Use YAML for Lovelace UI
lovelace:
  mode: yaml

# HomeKit setup
#homekit:
#  ip_address: "192.168.1.79"
#  filter:
#    include_domains: 
#      - light

frontend:
  themes: !include themes.yaml

# !includes for platforms
# influxdb: !include influxdb.yaml
alarm_control_panel: !include alarm.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
dyson: !include dyson.yaml
fan: !include fans.yaml
group: !include groups.yaml
http: !include http.yaml
input_select: !include input_selects.yaml
media_player: !include media_players.yaml
mqtt: !include mqtt.yaml
notify: !include notifiers.yaml
person: !include person.yaml
proximity: !include proximity.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
tts: !include tts.yaml
weather: !include weather.yaml
zone: !include zones.yaml

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_countrycode

speedtestdotnet:

