homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 35
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Brisbane
  # Customization file
  customize: !include customize.yaml
  # Auth Providers
  auth_providers:
   - type: legacy_api_password
     api_password: !secret api_password
   - type: homeassistant

# Automatically load default platforms
default_config:
discovery:
ssdp:
zeroconf:
# Use the recorder
recorder:
# Use the logbook
logbook:
# Activate the configuration editor
config:
  
# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Force load of IOS component
ios:

# Allow camera streaming
stream:

# Use YAML for Lovelace UI
lovelace:
  mode: yaml

# InfluxDB for time series history
influxdb:
  host: 192.168.1.72
  database: hass

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
http: !include http.yaml
sensor: !include sensors.yaml
  
# Weather prediction
weather:
  - platform: darksky
    name: Weather
    api_key: !secret darksky_api_key
    mode: daily

# Text to speech
tts:
  - platform: google_translate


# This platform allows you to detect presence by looking at devices connected to a Ubiquiti Unifi controller.
device_tracker: !include device_trackers.yaml

# Cameras
camera: !include cameras.yaml

# Dyson Platform
dyson:
  username: !secret dyson_username
  password: !secret dyson_password
  language: AU
  devices:
    - device_id: !secret dyson_fan1
      device_ip: 192.168.1.165
    - device_id: !secret dyson_fan2
      device_ip: 192.168.1.123

# MQTT Platform
mqtt:
  broker: !secret mqtt_broker
  port: 1884
  username: !secret mqtt_username
  password: !secret mqtt_password
  
# MQTT Motion Sensors from BlueIris
binary_sensor:
  - platform: mqtt
    name: "Front Door Motion"
    state_topic: "BlueIris/motion/frontdoor/"
    payload_on: "motion"
    payload_off: "off"
    availability_topic: "BlueIris/app"
    payload_available: "running"
    payload_not_available: "stopped"
    qos: 0
    device_class: motion
    
  - platform: mqtt
    name: "Lounge Room Motion"
    state_topic: "BlueIris/motion/loungeroom/"
    payload_on: "motion"
    payload_off: "off"
    availability_topic: "BlueIris/app"
    payload_available: "running"
    payload_not_available: "stopped"
    qos: 0
    device_class: motion

  - platform: mqtt
    name: "Garage Motion"
    state_topic: "BlueIris/motion/garage/"
    payload_on: "motion"
    payload_off: "off"
    availability_topic: "BlueIris/app"
    payload_available: "running"
    payload_not_available: "stopped"
    qos: 0
    device_class: motion

  - platform: mqtt
    name: "Media Room Motion"
    state_topic: "BlueIris/motion/mediaroom/"
    payload_on: "motion"
    payload_off: "off"
    availability_topic: "BlueIris/app"
    payload_available: "running"
    payload_not_available: "stopped"
    qos: 0
    device_class: motion

  - platform: mqtt
    name: "Back Yard Motion"
    state_topic: "BlueIris/motion/backyard/"
    payload_on: "motion"
    payload_off: "off"
    availability_topic: "BlueIris/app"
    payload_available: "running"
    payload_not_available: "stopped"
    qos: 0
    device_class: motion

# Media Players
media_player:
  - platform: samsungtv
    name: "Lounge TV"
    host: 192.168.1.204
    port: 8001
    
  - platform: onkyo
    host: 192.168.1.121
    name: "Media Room Receiver"

switch:
# MQTT Switches
  - platform: mqtt
    name: "Garage Door"
    state_topic: "home/doors/output/garagedoor"
    state_on: "ON"
    state_off: "OFF"
    command_topic: "home/doors/output/garagedoor/set_on_ms"
    payload_on: "500"
    availability_topic: "home/doors/status"
    payload_available: "running"
    payload_not_available: "dead"
    optimistic: false
    qos: 0
    retain: false

  - platform: mqtt
    name: "Front Door"
    state_topic: "home/doors/output/frontdoor"
    state_on: "ON"
    state_off: "OFF"
    command_topic: "home/doors/output/frontdoor/set_on_ms"
    payload_on: "5000"
    availability_topic: "home/doors/status"
    payload_available: "running"
    payload_not_available: "dead"
    optimistic: false
    qos: 0
    retain: false

# Template Entities
  - platform: template
    switches:
      media_room_activity_foxtel:
        value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Watch Foxtel') }}"
        turn_on:
          service: remote.turn_on
          data:
            entity_id: remote.harmony_hub
            activity: 'Watch Foxtel'
        turn_off:
          service: remote.turn_off
          data:
            entity_id: remote.harmony_hub

alarm_control_panel:
  - platform: manual
    code: !secret alarm_code

notify:
  - name: fb-gazzzmo
    platform: facebook
    page_access_token: !secret facebook_token

input_select:
  camera_dropdown:
    name: Cast camera
    options:
      - Backyard
      - Frontdoor
      - Garage
      - Lounge Room
      - Media Room
      - Cycle Cameras
      - All Cameras
    initial: All Cameras
    icon: mdi:webcam
  cast_to_screen_dropdown:
    name: To Screen
    options:
      - Media Room
      - Terrace
      - Tim Bedroom
    initial: Media Room
    icon: mdi:cast