title: Home
views:

### MAIN TAB ###
- title: Main
  path: main
  cards:
  - type: weather-forecast
    entity: weather.weather
  - type: horizontal-stack
    cards:
      - type: entity-button
        entity: light.front_door
      - type: entity-button
        entity: light.garage
      - type: entity-button
        entity: light.media_room
      - type: entity-button
        entity: light.lounge_room
  - type: entity-button
    entity: binary_sensor.lounge_room_motion
    icon_height: 64
  - type: entities
    entities:
    - sensor.aircon_state
  - type: conditional
    conditions:
      - entity: sensor.aircon_state
        state:  "on"
    card:
      type: entities
      entities:
      - sensor.aircon_mode
      - sensor.aircon_set_temperature
      - sensor.aircon_fan_speed
      - fan.aircon_fan
  - type: entities
    entities: 
    - type: section
      label: Upstairs
    - sensor.kitchen_family_temp
    - sensor.media_room_temp
    - sensor.lounge_room_temp
    - type: section
      label: Bedrooms
    - sensor.bed_1_temp
    - sensor.bed_2_temp
    - sensor.bed_3_temp
    - sensor.bed_4_temp

- title: Media Room
  path: mediaroom
  cards:
  - type: light
    entity: light.media_room
  - type: entities
    entities:
      - sensor.media_room_temp
      - sensor.media_room_state
  - type: media-control
    entity: media_player.kitchen

- title: Cameras
  path: cameras
  cards:
  - type: picture-entity
    entity: camera.backyard
    aspect_ratio: 16:9
  - type: picture-entity
    entity: camera.loungeroom
    aspect_ratio: 16:9

- title: Gareth
  # From: https://community.home-assistant.io/t/show-off-your-picture-elements-uses/63642/18?u=gazzzmo
  cards:
  - type: picture-elements
    image: /local/gareth.png
    elements:
      - style:
          top: 50%
          left: 50%
          width: 100%
        type: image
        entity: input_select.matte_home_status
        state_image:
          "Home": /local/ll_matte_home.png
          "Just Arrived": /local/ll_matte_home.png
          "Away": /local/ll_matte_not_home.png
          "Just Left": /local/ll_matte_not_home.png
          "Extended Away": /local/ll_matte_not_home.png
      - style:
          top: 50%
          left: 50%
          width: 100%
        type: image
        entity: input_boolean.matte_charging
        state_image:
          "on": /local/ll_status_charging1.png
          "off": /local/ll_status_blank.png
      - style:
          color: white
          top: 9%
          left: 12%
        type: state-icon
        entity: sensor.matte_battery
      - style:
          color: white
          top: 92%
          left: 50%
        type: state-label
        entity: sensor.matte_presence
      - style:
          color: white
          top: 10%
          left: 89%
        type: state-label
        entity: sensor.matte_battery
      - style:
          color: white
          top: 73%
          left: 88%
        type: state-label
        entity: proximity.home_gareth
      - style:
          color: white
          top: 73%
          left: 12%
        type: state-label
        entity: sensor.matte_hem