title: Home
views:

### MAIN TAB ###
- title: Main
  path: main
  cards:
  - type: weather-forecast
    entity: weather.weather
  - type: horizontal-stack
    cards:
      - type: entity-button
        entity: light.front_door
      - type: entity-button
        entity: light.garage
      - type: entity-button
        entity: light.media_room
      - type: entity-button
        entity: light.lounge_room
  - type: entities
    entities:
    - sensor.aircon_state
  - type: conditional
    conditions:
      - entity: sensor.aircon_state
        state:  "on"
    card:
      type: entities
      entities:
      - sensor.aircon_mode
      - sensor.aircon_set_temperature
      - sensor.aircon_fan_speed
      - fan.aircon_fan
  - type: entities
    entities: 
    - sensor.kitchen_family_temp
    - sensor.media_room_temp
    - sensor.lounge_room_temp
    - sensor.bed_1_temp
    - sensor.bed_2_temp
    - sensor.bed_3_temp
    - sensor.bed_4_temp

- title: Media Room
  path: mediaroom
  cards:
  - type: light
    entity: light.media_room
  - type: sensor
    entity: sensor.media_room_temp
  - type: media-control
    entity: media_player.kitchen