title: Home
views:

### MAIN TAB ###
- title: Main
  path: main
  theme: google-light
  cards:
  - type: vertical-stack
    cards:
    - type: weather-forecast
      entity: weather.darksky_weather
      name: "Weather"
    - type: horizontal-stack
      cards:
      - type: markdown
        content: |
          ### Media Room

          # {{ states('sensor.media_room_temp') }}ยบ
      - type: markdown
        content: |
          ### Kitchen

          # {{ states('sensor.kitchen_temp') }}ยบ
      - type: markdown
        content: |
          ### Bedrooms

          # {{ states('sensor.parents_bedroom_temp') }}ยบ
    - type: vertical-stack
      cards:
      - type: entities
        entities:
        - sensor.aircon_state
      - type: conditional
        conditions:
          - entity: sensor.aircon_state
            state: "on"
        card:
          type: entities
          entities:
            - sensor.aircon_mode
            - sensor.aircon_set_temperature
            - sensor.aircon_fan_speed
            - fan.aircon_fan
  - type: vertical-stack
    cards:
    - type: custom:mini-graph-card
      name: NBN
      group_by: hour
      decimals: 1
      lower_bound: 0
      upper_bound: 100
      lower_bound_secondary: 0
      upper_bound_secondary: 500
      entities:
      - entity: sensor.speedtest_download
        name: Download
        color: red
      - entity: sensor.speedtest_upload
        name: Upload
        color: orange
      - entity: sensor.speedtest_ping
        name: Ping
        color: gray
        y_axis: secondary
    - type: custom:auto-entities
      show_empty: false
      card:
        type: entities
        title: Lights
      filter:
        include:
         - domain: light
           options:
            tap_action:
              action: toggle
  - type: vertical-stack
    cards:
    - type: custom:mini-graph-card
      name: Coronavirus
      group_by: date
      hours_to_show: 168
      icon: mdi:hospital-marker
      entities:
      - entity: sensor.australia_coronavirus_confirmed
        name: Confirmed
        color: gray
      - entity: sensor.australia_coronavirus_current
        name: Current
        color: orange
      - entity: sensor.australia_coronavirus_deaths
        name: Deaths
        color: red
      - entity: sensor.australia_coronavirus_recovered
        name: Recovered
        color: green
    - type: picture-glance
      title: Garage
      camera_image: camera.garage
      entities:
        - switch.garage_door
      tap_action:
        action: call-service
        service: switch.turn_on
        service_data:
          entity_id: switch.garage_door
    - type: picture-glance
      title: Driveway
      camera_image: camera.driveway
      entities:
        - camera.driveway
    - type: picture-glance
      title: Back Deck
      camera_image: camera.back_deck
      entities:
        - camera.back_deck

### FAMILY TAB
- title: Family
  path: family
  cards:
  - type: map
    entities:
      - person.gareth
      - person.mandy
      - person.jess
      - person.jess

### MEDIA ROOM TAB ###
- title: Media Room
  path: mediaroom
  cards:
  - type: vertical-stack
    cards:
    - type: markdown
      content: |
        ### Activity

        # {{ states('sensor.mediaroom_activity') }}
    - type: custom:mini-media-player
      entity: media_player.media_room_receiver
      icon: mdi:amplifier
      volume_stateless: true
    - type: horizontal-stack
      cards:
      - type: button
        name: Watch Foxtel
        icon: mdi:television
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.1546774194124
      - type: button
        name: Turn Off
        icon: mdi:power-off
        tap_action:
          action: call-service
          service: script.turn_on
          service_data:
            entity_id: script.1546773277389
  - type: vertical-stack
    cards:
    - type: light
      entity: light.media_room_lamp
    - type: entities
      entities:
        - sensor.media_room_temp
        - sensor.media_room_state

### JESS
- title: Jess
  path: jess
  cards:
  - type: entities
    entities:
    - fan.jess_bedroom
    - light.jess_bedside
    - media_player.jess_chromecast
    - sensor.jess_bedroom_aqi
    - sensor.jess_bedroom_dust
    - sensor.jess_bedroom_humidity
    - sensor.jess_bedroom_filter_life
    - sensor.jess_bedroom_state
    - sensor.jess_bedroom_temp
    - sensor.jess_bedroom_temperature
    - device_tracker.jessicas_iphone

### SONOS TAB ###
- title: Sonos
  path: sonos
  cards:
  - type: entities
    entities:
      - type: custom:mini-media-player
        entity: media_player.lounge
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.terrace
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.upstairs
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.ensuite
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.foyer
        icon: mdi:cast-audio

### SECURITY TAB ###
- title: Security
  path: security
  theme: google-light
  cards:
  - type: vertical-stack
    cards:
      - type: picture-entity
        entity: camera.back_deck
        camera_image: camera.back_deck
        camera_view: live
      - type: picture-entity
        entity: camera.driveway
        camera_image: camera.driveway
        camera_view: live
  - type: vertical-stack
    cards:
    - type: picture-entity
      entity: camera.lounge_room
      camera_image: camera.lounge_room
      camera_view: live
    - type: picture-entity
      entity: camera.front_door
      camera_image: camera.front_door
      camera_view: live
  - type: vertical-stack
    cards:
    - type: picture-entity
      entity: camera.side_stairs
      camera_image: camera.side_stairs
      camera_view: live
    - type: picture-entity
      entity: camera.garage
      camera_image: camera.garage
      camera_view: live
#    - type: glance
#      title: Motion
#      entities:
#      - entity: binary_sensor.front_door_motion
#        name: Front Door
#      - entity: binary_sensor.garage_motion
#        name: Garage
#      - entity: binary_sensor.driveway_motion
#        name: Driveway
#      - entity: binary_sensor.lounge_room_motion
#        name: Lounge Room
#      - entity: binary_sensor.back_deck_motion
#        name: Back Deck
#      - entity: binary_sensor.side_stairs_motion
#        name: Side Stairs

### GARAGE TAB ###
- title: Garage
  path: garage
  theme: google-light
  cards:
    - type: picture-entity
      entity: camera.garage
      camera_view: live
    - type: horizontal-stack
      cards:
      - type: entity-button
        entity: switch.garage_door
        icon: mdi:garage
      - type: light
        entity: light.garage_lamp

### AIRCON TAB ###
- title: Aircon
  path: aircon
  theme: google-light
  cards:
    - type: vertical-stack
      cards:
      - type: entities
        entities:
        - sensor.aircon_state
      - type: conditional
        conditions:
          - entity: sensor.aircon_state
            state: "on"
        card:
          type: entities
          entities:
          - sensor.aircon_mode
          - sensor.aircon_set_temperature
          - sensor.aircon_fan_speed
          - fan.aircon_fan
      - type: entities
        entities: 
        - type: section
          label: Upstairs
        - sensor.kitchen_temp
        - sensor.media_room_temp
        - sensor.office_temp
        - type: section
          label: Bedrooms
        - sensor.parents_bedroom_temp
        - sensor.tim_bedroom_temp
        - sensor.study_temp
        - sensor.jess_bedroom_temp  

### SYSTEMS TAB ###
- title: Systems
  path: systems
  cards:
      - type: entities
        title: "SSL Certificate Expiry"
        show_header_toggle: off
        entities:
          - sensor.hass_cert
          - sensor.cams_cert
          - sensor.unifi_cert
      - type: entities
        title: "HASS Update"
        show_header_toggle: off
        entities:
          - binary_sensor.updater
      - type: entities
        title: "Hass Host"
        show_header_toggle: off
        entities:
          - sensor.processor_use
          - sensor.memory_free
          - sensor.disk_use_percent_home
      - type: custom:mini-graph-card
        name: Speedtest
        group_by: hour
        decimals: 1
        lower_bound: 0
        upper_bound: 100
        lower_bound_secondary: 0
        upper_bound_secondary: 500
        entities:
          - entity: sensor.speedtest_download
            name: Download
            color: red
          - entity: sensor.speedtest_upload
            name: Upload
            color: orange
          - entity: sensor.speedtest_ping
            name: Ping
            color: gray
            y_axis: secondary