title: Home
views:

### OVERVIEW TAB ###
- title: Overview
  path: overview
  cards:
    - type: picture-glance
      title: Lounge Room
      camera_image: camera.loungeroom
      entities:
        - binary_sensor.lounge_room_motion
        - media_player.lounge
        - media_player.lounge_cast
        - light.lounge_room

    - type: picture-glance
      title: Media Room
      camera_image: camera.mediaroom
      entities:
        - binary_sensor.media_room_motion
        - remote.harmony_hub
        - sensor.mediaroom_activity
        - light.media_room_left
        - light.media_room_right

    - type: picture-glance
      title: Front Yard
      camera_image: camera.frontdoor
      entities:
        - binary_sensor.front_door_motion
        - switch.front_door

    - type: picture-glance
      title: Garage
      camera_image: camera.garage
      entities:
        - binary_sensor.garage_motion
        - media_player.garage
        - switch.garage_door
        - light.garage

    - type: picture-glance
      title: Backyard
      camera_image: camera.backyard
      entities:
        - binary_sensor.back_yard_motion
        - media_player.terrace
        - media_player.terrace_chromcast

### FAMILY TAB ###
- title: Family
  path: family
  cards:
    - type: horizontal-stack
      cards:
      - type: picture-entity
        title: Gareth
        entity: device_tracker.garethiphone
        image: /local/gareth.png
        name: Gareth
      - type: picture-entity
        title: Mandy
        entity: device_tracker.mandyiphone
        image: /local/mandy.png
        name: Mandy
    - type: horizontal-stack
      cards:
      - type: picture-entity
        title: Tim
        entity: device_tracker.timiphone
        image: /local/tim.png
        name: Tim
      - type: picture-entity
        title: Jess
        entity: device_tracker.jessicasiphone
        image: /local/jess.png
        name: Jess
    - type: map
      default_zoom: 11
      entities:
      - device_tracker.garethiphone
      - device_tracker.mandyiphone
      - device_tracker.timiphone
      - device_tracker.jessicasiphone

### TIM TAB ###
- title: Tim
  path: tim
  cards:
    - type: glance
      title: Tim Bedroom
      entities:
        - fan.tim_bedroom
        - light.lifx_mini_d_3de6c0
        - light.tim_bedroom_left
        - light.tim_bedroom_right
    - type: entities
      show_header_toggle: false
      entities:
        - entity: input_number.tim_fan_speed
    - type: sensor
      name: Temperature
      entity: sensor.tim_bedroom_temperature
      graph: line
      detail: 2
    - type: media-control
      name: Tim TV
      entity: media_player.tim_ua43mu6100
    - type: media-control
      entity: media_player.apple_tv
    - type: media-control
      entity: media_player.tim_chromecast

### JESS TAB ###  
- title: Jess
  path: jess
  cards:
    - type: glance
      title: Jess Bedroom
      entities:
        - fan.jess_bedroom
        - light.jess
    - type: horizontal-stack
      cards:
      - type: gauge
        name: Temperature
        entity: sensor.jess_bedroom_temperature
        min: 0
        max: 50
        severity:
          green: 0
          yellow: 30
          red: 40
      - type: gauge
        name: Humidity
        entity: sensor.jess_bedroom_humidity
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 80

### PARENTS TAB ###
- title: Parents
  path: parents
  cards:
    - type: glance
      title: Parents Bedroom
      entities:
        - media_player.parents_bedroom
        - light.parents_bedhead
        - light.parents_bedroom_2

### SECURITY TAB ###
- title: Security
  path: security
  cards:
    - type: alarm-panel
      name: Alarm
      entity: alarm_control_panel.ha_alarm
    - type: entities
      title: "Cast Camera to Screen"
      entities:
       - input_select.camera_dropdown
       - input_select.cast_to_screen_dropdown
       - script.execute_cast_dropdown

### WEATHER TAB ###
- title: Weather
  path: weather
  cards:
    - type: weather-forecast
      title: Weather Forecast
      entity: weather.weather
    - type: history-graph
      title: 'Temperature'
      entities:
        - entity: sensor.weather_temperature
          name: "Outside Temperature"
        - entity: sensor.aeotec_zw100_multisensor_6_temperature
          name: "Media Room"
        - entity: sensor.jess_bedroom_temperature
          name: "Jess Bedroom"
        - entity: sensor.tim_bedroom_temperature
          name: "Tim Bedroom"

### MEDIAROOM TAB ###
- title: Media Room
  path: mediaroom
  cards:
    - type: horizontal-stack
      cards:
        - type: entity-button
          name: Rewind
          entity: remote.harmony_hub
          icon: mdi:rewind
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Rewind
        - type: entity-button
          name: Play
          entity: remote.harmony_hub
          icon: mdi:play
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Play
        - type: entity-button
          name: Fast Forward
          entity: remote.harmony_hub
          icon: mdi:fast-forward
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Fast Forward

    - type: horizontal-stack
      cards:
        - type: entity-button
          name: Record
          entity: remote.harmony_hub
          icon: mdi:record
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Record
        - type: entity-button
          name: Pause
          entity: remote.harmony_hub
          icon: mdi:pause
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Pause
        - type: entity-button
          name: Stop
          entity: remote.harmony_hub
          icon: mdi:stop
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Stop

    - type: horizontal-stack
      cards:
        - type: entity-button
          name: Red
          entity: remote.harmony_hub
          icon: mdi:minus
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Green
        - type: entity-button
          name: Green
          entity: remote.harmony_hub
          icon: mdi:minus
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Pause
        - type: entity-button
          name: Yellow
          entity: remote.harmony_hub
          icon: mdi:minus
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Stop
        - type: entity-button
          name: Blue
          entity: remote.harmony_hub
          icon: mdi:minus
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Stop


    - type: horizontal-stack
      cards:
        - type: entity-button
          name: Guide
          entity: remote.harmony_hub
          icon: mdi:television-guide
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Guide
        - type: entity-button
          name: Up
          entity: remote.harmony_hub
          icon: mdi:arrow-up
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: DirectionUp
        - type: entity-button
          name: Library
          entity: remote.harmony_hub
          icon: mdi:library
          tap_action:
            action: call-service
            service: remote.send_command
            service_data:
              entity_id: remote.harmony_hub
              device: 35606761
              command: Library

    - type: horizontal-stack
      cards:
        - type: picture-entity
          entity: script.1547214476595
          image: "/local/Foxtel_Entertainment_Fox8.png"
          show_name: false
          show_state: false
    - type: horizontal-stack
      cards:
      - type: gauge
        name: Temperature
        entity: sensor.aeotec_zw100_multisensor_6_temperature
        min: 0
        max: 50
        severity:
          green: 0
          yellow: 30
          red: 40
      - type: gauge
        name: Humidity
        entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
        min: 0
        max: 100
        severity:
          green: 0
          yellow: 50
          red: 80

### SONOS TAB ###
- title: Sonos
  path: sonos
  cards:
    - type: vertical-stack
      cards:
        - type: media-control
          entity: media_player.garage
        - type: media-control
          entity: media_player.kitchen
        - type: media-control
          entity: media_player.lounge
        - type: media-control
          entity: media_player.terrace

### SYSTEMS TAB ###
- title: Systems
  path: systems
  cards:
    - type: vertical-stack
      cards:
        - type: entities
          title: SSL Certificates
          show_header_toggle: false
          entities:
            - sensor.cams_cert
            - sensor.unifi_cert
            - sensor.hass_cert
        - type: entities
          title: Hass.io Host
          show_header_toggle: false
          entities:
            - sensor.disk_use_percent_home
            - sensor.memory_free
            - sensor.uptime
        - type: gauge
          name: CPU Use
          entity: sensor.processor_use
          min: 0
          max: 100
          severity:
            green: 0
            yellow: 50
            red: 80
        - type: entity-button
          entity: sensor.uptime
          tap_action:
            action: call-service
            service: hassio.host_reboot

