title: Home

resources:
  - url: /local/mini-media-player-bundle.js?v=142
    type: module
  - url: /local/auto-entities.js?v=13
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.8.2
    type: module

views:

### OVERVIEW TAB ###
- title: Overview
  path: overview
  cards:
  - type: custom:auto-entities
    show_empty: false
    card:
      type: glance
      title: Lights
    filter:
      include:
       - domain: light
         options:
          tap_action:
            action: toggle
    sort: name
  - type: custom:auto-entities
    show_empty: false
    card:
      type: glance
      title: Motion
    filter:
      include:
       - entity_id: "binary_sensor.*motion"
    sort: name

### MAIN TAB ###
- title: Main
  path: main
  cards:
  - type: vertical-stack
    cards:
    - type: weather-forecast
      entity: weather.open_weather_map
      name: Brisbane Weather
    - type: horizontal-stack
      cards:
      - type: entity-button
        entity: switch.garage_door
        icon: mdi:garage
        icon_height: 50
    - type: picture-entity
      entity: camera.brisbane_weather_radar
      camera_view: live
    - type: horizontal-stack
      cards:
        - type: entity-button
          entity: light.front_door
        - type: entity-button
          entity: light.garage
        - type: entity-button
          entity: light.media_room
        - type: entity-button
          entity: light.lounge_room

- title: Media Room
  path: mediaroom
  cards:
  - type: vertical-stack
    cards:
    - type: entities
      entities:
        - sensor.mediaroom_activity
    - type: custom:mini-media-player
      entity: media_player.media_room_receiver
    - type: light
      entity: light.media_room
    - type: entities
      entities:
        - sensor.media_room_temp
        - sensor.media_room_state

- title: Sonos
  path: sonos
  cards:
  - type: entities
    entities:
      - type: custom:mini-media-player
        entity: media_player.lounge
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.terrace
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.upstairs
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.ensuite
        icon: mdi:cast-audio
      - type: custom:mini-media-player
        entity: media_player.foyer
        icon: mdi:cast-audio

- title: Security
  path: security
  cards:
  - type: vertical-stack
    cards:
    - type: alarm-panel
      entity: alarm_control_panel.ha_alarm
      name: Alarm
      states:
      - arm_home
      - arm_away
      - arm_night
    - type: horizontal-stack
      cards:
      - type: glance
        title: Motion
        entities:
        - entity: binary_sensor.front_door_motion
          name: Front Door
        - entity: binary_sensor.garage_motion
          name: Garage
        - entity: binary_sensor.driveway_motion
          name: Driveway
        - entity: binary_sensor.lounge_room_motion
          name: Lounge Room
        - entity: binary_sensor.back_deck_motion
          name: Back Deck
        - entity: binary_sensor.side_stairs_motion
          name: Side Stairs

- title: Cameras
  path: cameras
  cards:
  - type: picture-entity
    entity: camera.back_deck
    camera_image: camera.back_deck
    camera_view: live
  - type: picture-entity
    entity: camera.driveway
    camera_image: camera.driveway
    camera_view: live
  - type: picture-entity
    entity: camera.lounge_room
    camera_image: camera.lounge_room
    camera_view: live
  - type: picture-entity
    entity: camera.front_door
    camera_image: camera.front_door
    camera_view: live
  - type: picture-entity
    entity: camera.side_stairs
    camera_image: camera.side_stairs
    camera_view: live
  - type: picture-entity
    entity: camera.garage
    camera_image: camera.garage
    camera_view: live

- title: Garage
  path: garage
  cards:
    - type: picture-entity
      entity: camera.garage
      camera_image: camera.garage
      camera_view: live
    - type: entities
      entities:
      - entity: switch.garage_door
        icon: mdi:garage
      - entity: light.garage

- title: Aircon
  path: aircon
  cards:
    - type: vertical-stack
      cards:
      - type: entities
        entities:
        - sensor.aircon_state
      - type: conditional
        conditions:
          - entity: sensor.aircon_state
            state: "on"
        card:
          type: entities
          entities:
          - sensor.aircon_mode
          - sensor.aircon_set_temperature
          - sensor.aircon_fan_speed
          - fan.aircon_fan
      - type: entities
        entities: 
        - type: section
          label: Upstairs
        - sensor.kitchen_temp
        - sensor.media_room_temp
        - sensor.office_temp
        - type: section
          label: Bedrooms
        - sensor.parents_bedroom_temp
        - sensor.tim_bedroom_temp
        - sensor.study_temp
        - sensor.jess_bedroom_temp  

- title: Systems
  path: systems
  # Monitor and control systems
  cards:
      - type: entities
        title: "SSL Certificate Expiry"
        show_header_toggle: off
        entities:
          - sensor.hass_cert
          - sensor.cams_cert
          - sensor.unifi_cert
      - type: entities
        title: "Hass Host"
        show_header_toggle: off
        entities:
          - sensor.processor_use
          - sensor.memory_free
          - sensor.disk_use_percent_home
      - type: custom:mini-graph-card
        name: Speedtest
        group_by: hour
        decimals: 1
        entities:
          - entity: sensor.speedtest_download
            name: Download
            color: red
          - entity: sensor.speedtest_upload
            name: Upload
            color: orange
          - entity: sensor.speedtest_ping
            name: Ping
            color: gray