title: Home
views:

### MAIN TAB ###
- title: Main
  path: main
  cards:
    - type: vertical-stack
      cards:
        - type: guage
          entity: sensor.bed_1_temp
        - type: guage
          entity: sensor.bed_2_temp
        - type: guage
          entity: sensor.bed_3_temp
        - type: guage
          entity: sensor.bed_4_temp
          