### SECURITY TAB ###
title: Security
path: security
theme: google-light
cards:
- type: vertical-stack
  cards:
    - type: picture-entity
      entity: camera.back_deck
      camera_image: camera.back_deck
      camera_view: live
    - type: entities
      entities: 
      - binary_sensor.back_deck_motion
    - type: picture-entity
      entity: camera.driveway
      camera_image: camera.driveway
      camera_view: live
    - type: entities
      entities: 
      - binary_sensor.driveway_motion
- type: vertical-stack
  cards:
  - type: picture-entity
    entity: camera.lounge_room
    camera_image: camera.lounge_room
    camera_view: live
  - type: entities
    entities:
    - binary_sensor.lounge_room_motion
  - type: picture-entity
    entity: camera.front_door
    camera_image: camera.front_door
    camera_view: live
  - type: entities
    entities:
    - binary_sensor.front_door_motion
- type: vertical-stack
  cards:
  - type: picture-entity
    entity: camera.side_stairs
    camera_image: camera.side_stairs
    camera_view: live
  - type: entities
    entities:
    - binary_sensor.side_stairs_motion
  - type: picture-entity
    entity: camera.garage
    camera_image: camera.garage
    camera_view: live
  - type: entities
    entities:
    - binary_sensor.garage_motion
